name: Test Self-Hosted Runner
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted  # Используем наш runner
    # Или с конкретными метками:
    # runs-on: [self-hosted, linux, ubuntu]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check system info
      run: |
        echo "Runner OS: $(uname -a)"
        echo "Current user: $(whoami)"
        echo "Working directory: $(pwd)"
        echo "Available space: $(df -h .)"
    # - name: nstall uv
    - name: Install Python dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source /root/.local/bin/env
        uv sync
    
    - name: Run tests
      run: |
        uv run main.py || echo "No tests found"
